stages:
  - build
  # - deploy

variables:
  CI_REGISTRY_IMAGE: 10.1.3.188:5000/skynet-web

build:
  stage: build
  tags: [centos7]
  script: 
    - docker build --rm -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-latest
    
# deploy:
#   stage: deploy
#   image: 10.1.3.188:5000/kubelet:71
#   script: 
#     - sed -i s/latest/${CI_PIPELINE_ID}/ atx.yml
#     - kubectl apply -f atx.yml
